/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_client/serverpod_client.dart' as _i1;

/// AI insight generated by the agent system
abstract class AIInsight implements _i1.SerializableModel {
  AIInsight._({
    required this.id,
    required this.message,
    required this.category,
    required this.generatedAt,
    required this.isDismissed,
  });

  factory AIInsight({
    required String id,
    required String message,
    required String category,
    required DateTime generatedAt,
    required bool isDismissed,
  }) = _AIInsightImpl;

  factory AIInsight.fromJson(Map<String, dynamic> jsonSerialization) {
    return AIInsight(
      id: jsonSerialization['id'] as String,
      message: jsonSerialization['message'] as String,
      category: jsonSerialization['category'] as String,
      generatedAt: _i1.DateTimeJsonExtension.fromJson(
        jsonSerialization['generatedAt'],
      ),
      isDismissed: jsonSerialization['isDismissed'] as bool,
    );
  }

  /// Unique identifier
  String id;

  /// The insight message content
  String message;

  /// Insight category (suggestion, warning, encouragement, pattern)
  String category;

  /// When this insight was generated
  DateTime generatedAt;

  /// Whether the user has dismissed this insight
  bool isDismissed;

  /// Returns a shallow copy of this [AIInsight]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  AIInsight copyWith({
    String? id,
    String? message,
    String? category,
    DateTime? generatedAt,
    bool? isDismissed,
  });
  @override
  Map<String, dynamic> toJson() {
    return {
      '__className__': 'AIInsight',
      'id': id,
      'message': message,
      'category': category,
      'generatedAt': generatedAt.toJson(),
      'isDismissed': isDismissed,
    };
  }

  @override
  String toString() {
    return _i1.SerializationManager.encode(this);
  }
}

class _AIInsightImpl extends AIInsight {
  _AIInsightImpl({
    required String id,
    required String message,
    required String category,
    required DateTime generatedAt,
    required bool isDismissed,
  }) : super._(
         id: id,
         message: message,
         category: category,
         generatedAt: generatedAt,
         isDismissed: isDismissed,
       );

  /// Returns a shallow copy of this [AIInsight]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  @override
  AIInsight copyWith({
    String? id,
    String? message,
    String? category,
    DateTime? generatedAt,
    bool? isDismissed,
  }) {
    return AIInsight(
      id: id ?? this.id,
      message: message ?? this.message,
      category: category ?? this.category,
      generatedAt: generatedAt ?? this.generatedAt,
      isDismissed: isDismissed ?? this.isDismissed,
    );
  }
}
